---
variables:
  LEKTOR_BUILD_FLAGS: scss
  SITE_URL: newsletter.torproject.org
  STAGING_URL: newsletter.staging.torproject.net

include:
  project: tpo/tpa/ci-templates
  file:
    - lektor.yml
    - static-shim-deploy.yml
